### ISSUE TITLE
Where to write import statements from node modules?

### ISSUE THREAD

**Issue by donjae** [jeffijoe/koa-es7-boilerplate#2]
Hi,
It wasn't really clearly stated, but if I wanted to import other node modules, would I put it in the `lib/createServer.js` or whatever service file I make (ie. `services/myWhateverService.js`)? If it's for a database connections or something used globally, would it be better to import it in the former?

**Comment by jeffijoe** [comment]
Hi!

That depends on the usage pattern - utility libraries like `lodash` can be imported wherever you want, but if, say you're making a database object as a singleton (one instance for the lifetime of the process), then one place to do such initialization could definitely be in `createServer`.

However, since each service (or whatever _you_ choose to wire up with the DI container) is initialized at app startup, you could actually set up the connection in the default export, since Awilix supports async registrations.

Here's some code pulled from one of my projects that uses async registration:

``` js
export default async function createDb(container) {
  // Async!
  const db = await getDatabase();

  container.register({ db });
}
```

Does that help?

**Comment by donjae** [comment]
Thanks, yeah it really does help

**Comment by donjae** [comment]
@jeffijoe Actually, another question. But lets say I use that `export default async function createDb(container) {...}`

where should I define the `getDatabase` function/connection? Sorry about the dumb question. Not sure if this is more of a Awilix question or a question more so for this template**

**Comment by jeffijoe** [comment]
That's totally up to you. In the case above, it was a function in the same file.
